mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.78.93.113/testtest?autoReconnect=true&allowMultiQueries=true
    username: root
    password: Ccwh123!
server:
  port: 8086
